spring:
  application.name: formulier-beheer
  threads.virtual.enabled: true
server:
  address: 127.0.0.1
  port: 8385
spring.security.oauth2.client:
  registration:
    google-login:
      client-name: Google
      client-authentication-method: client_secret_basic
      authorization-grant-type: authorization_code
      redirect-uri: http://127.0.0.1:8385/login/oauth2/code/google
      scope:
        - openid
        - profile
        - email
        - https://www.googleapis.com/auth/drive
        - https://www.googleapis.com/auth/script.send_mail
        - https://www.googleapis.com/auth/spreadsheets
      provider: google-login
  provider:
    google-login:
      issuer-uri: https://accounts.google.com
      authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
      token-uri: https://www.googleapis.com/oauth2/v4/token
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
      user-name-attribute: sub
      jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs


# Formulier
implementation-id: AKfycbyAFMU7cxmosMqHCVnbUYhsLloevVWTawTJiQQD8hFyXrfT5gqPNeAxAZDBIDnITEA2
# runFunction
#implementation-id: AKfycbwCqy6fyMzNs6RwjB2VUfF6m2qbxi18KTEqeAQgUaRVVte-PkaDmL4EALkQfDwNLyFc